####################################
#   Auto Generated By FunctionEX   #
####################################

# Says Hello World!
say Hello World!

# Creates a variable named test
scoreboard players set @a test 1

# Suffocates player if test is 1
execute @a[score_test=1,score_test_min=1] ~ ~ ~ execute @p ~ ~ ~ tp ~ ~-10 ~